### ISSUE TITLE
An example using the "real" nodes on different machines (or processes)

### ISSUE THREAD

**Issue by AlexeyRaga** [transient-haskell/transient#5]
An example that shows how to use the distributed features on "real" nodes would be appreciated: how to create remote nodes, should `listen` be called only for the `local` node or for all nodes, how to wait until all the nodes connect, etc.

**Comment by agocorona** [comment]
Alex:
There is a runnable example at: https://ide.c9.io/agocorona/transienttest
clone it.
execute three node processes by:

    > cd transientinstaller
    > ./init.sh

a cluster of three nodes will be running.
Enter in the first node at port 8080 by pointing the browser to:  http://http://transienttest-<youruser>.c9users.io/

to enter in the second node: http://transienttest-agocorona.c9users.io:8081

to enter in the third node: http://transienttest-agocorona.c9users.io:8082

there you can execute a federated chat server and a map-reduce widget. Both widgets execute in the cluster. 

there is a link to the source code in the example.

**Comment by agocorona** [comment]
![transientt](https://cloud.githubusercontent.com/assets/522634/19530536/8a0fbf4e-9634-11e6-92fd-8f2a85006395.png)

**Comment by agocorona** [comment]
![transientt2](https://cloud.githubusercontent.com/assets/522634/19530757/6e085530-9635-11e6-9f3d-4a65dfae9ded.png)
