### ISSUE TITLE
threads primitive does not work as expected with logging

### ISSUE THREAD

**Issue by harendra-kumar** [transient-haskell/transient#56]
Consider this program:

```haskell
main = keep $ restore $ do
     r <- logged $ threads 3 $ choose [1..10 :: Int]
     logged $ liftIO $ print ("A",r)
     suspend ()
     logged $ liftIO $ print ("B",r)
```

This does not perform full 10 iterations.

**Comment by agocorona** [comment]
`restore`assumes that suspend saved info for all the work units. But suspend `exit` before finishing all the threads. It must not exit when there is no alternative thread waiting.

**Comment by agocorona** [comment]
The non-deterministic execution of transient precludes a way to assure that all the possible threads have passed trough the suspend point,  It can not guarantee it. if However we  detect that no threads remain active using the `threadBlockedInMVarOperation`exception used in `collect` that would imply that some computations would never suspend when some thread remain active waiting for some event. therefore this may be left as is, with all these caveats.
