### ISSUE TITLE
Lost or silently ignored exceptions

### ISSUE THREAD

**Issue by harendra-kumar** [transient-haskell/transient#61]
In the current implementation if there is no transient level exception handler installed we just silently ignore the IO exception. Consider this simple program:

```haskell
main = keep $ liftIO $ error "Raised ErrorCall exception" >> return ()
```

Instead we should re-raise the exception if there is no handler installed, so that it does not go unnoticed. See the `MonadIO` instance and the `back` function for relevant code.

**Comment by harendra-kumar** [comment]
Failure indication in transient is done via `empty` or `stop` which makes the computation return a `Nothing` value. So that way the exception is not really lost because we use `stop` even when there is no exception installed. And we can always check the return value to know whether the computation failed or succeeded. Though it is pretty silent. Is there a way around that?

**Comment by agocorona** [comment]
Yes. It is necessary a `SomeException` handler at the top level defined in `keep` that prints the error

**Comment by agocorona** [comment]
@harendra-kumar do you mean that in  the context of exceptions or in general?
 
I suggest to use a onException at the top level of the program.

```
keep $ do
   onException $\(e:: SomeException) -> liftIO $ print e
   code

Should print any exception backtracked to the top,  not redirected forward with `continue`

In a general sense,  a more loudier way to fail is possible by using Alternative. If we have a silent failing code `silent`that produce `empty`  then the loudier fail can be constructed with:

```haskell
        silent <|>  error "hey, silent failed"
```

**Comment by jberryman** [comment]
The approach taken by `async` is I think the right one with respect to exceptions and forked threads. I'm not sure how that would map to the DSL y'all use here.

**Comment by agocorona** [comment]
@jberryman  do you mean the (async library](http://tldrify.com/nf0)

It is right for that library. It has applicative composition.  Transient has monadic composition too. In transient the handlers are in the state of the monad and are applied to every thread.  When an exception happens, it executes every  of these handlers in reverse order, unless  `continue` stop this process and re-execute from that point.

Suppose this code in transient:

```haskell
  do      
            ....
            onException $ \(e :: SomeException) -> liftIO (print e) >> continue
            data <- (,) <$> async  download1  <*> async dowmload2
```

If either the first async thread of the second fail, this threads  executes the exception code,  and `continue` will force the re-execution of the download again.

That `onException` is not the one of Control.Monad.Exception,  but of Transient.Internals, which is different.

**Comment by agocorona** [comment]
Fixed in latest releases.  All exceptions are catched by the backtracking mechanism
