### ISSUE TITLE
Cannot use an untyped expression (e.g. error and throw) as the last expression

### ISSUE THREAD

**Issue by harendra-kumar** [transient-haskell/transient#62]
This program won't compile:

```haskell
main = keep $ error "Raised ErrorCall exception"
```

But this compiles fine:

```haskell
main = keep $ error "Raised ErrorCall exception" >> return ()
```

That's because keep has a `Typeable` constraint. Is there a way around this? If not we should at least document this behavior.

**Comment by agocorona** [comment]
the typeable is used by `exit` to return from the keep block. It can be called at any place of the computation and to check that the type match it needs the result to be typeable....
