### ISSUE TITLE
Inconsistent exception behavior

### ISSUE THREAD

**Issue by harendra-kumar** [transient-haskell/transient#63]
We catch the IO exceptions in the `MonadIO` instance and handle them using the backtracking mechanism. However exceptions that might be thrown in the transient monad itself are not caught and handled in the same way, they just escape outside. We must have a consistent exception handling.

**Comment by agocorona** [comment]
It seems that if the exceptions are tracked when they are produced in a different thread. I have a release that mitigate this problem, but I have to test it . I'm not sure if it solves all the problems.

**Comment by agocorona** [comment]
But It is possible to place an exception handler in the `onException` site to track these non redirected exceptions: My first take is:

```haskell
onException' :: Exception e => TransIO a -> (e -> TransIO a) -> TransIO a
onException' mx f= onAnyException mx $ \e ->
    case fromException e of
       Nothing -> empty
       Just e'  -> f e'
  where
  onAnyException :: TransIO a -> (SomeException ->TransIO a) -> TransIO a
  onAnyException mx f=  Transient $ do
        st <- get
        (ma,st') <-liftIO $ runStateT ( runTrans $ mx `onBack`  f) st 
                                  `catch` (\(e ::SomeException) -> runStateT ( runTrans $ f e) st )
        put st'
        return ma
``` 

Seems to work  and even backtrack to previous `onException` . But it needs more test.

**Comment by agocorona** [comment]
This seems to work fro  computations inside liftIO and outside.

```haskell
onException :: Exception e => (e -> TransIO ()) -> TransIO ()
onException exc= return () `onException'` exc


onException' :: Exception e => TransIO a -> (e -> TransIO a) -> TransIO a
onException' mx f= onAnyException mx $ \e ->
    case fromException e of
       Nothing -> empty
       Just e'  -> f e'
  where
  onAnyException :: TransIO a -> (SomeException ->TransIO a) -> TransIO a
  onAnyException mx f=  do
      mx `onBack`  f
      Transient $ do
        st <- get
        case event st of 
          Nothing ->   do 
             x <- runTrans  mx 
             liftIO $  runCont' st{event= Just $ unsafeCoerce x} 
                         `catch` (\(e ::SomeException) -> runStateT ( runTrans $ back e  ) st  )
             return Nothing
          Just val -> do
               put  st{event=Nothing} 
               return $  unsafeCoerce val
```

I tested it with

main= keep $ do
    onException $ \(e :: SomeException) -> liftIO (putStrLn $ show e ++ " 2222222222")
    onException $ \(e :: SomeException) -> liftIO (putStrLn $ show e ++ " 1111111111") 
    error "hello"
    return ()
```

and also with  `liftIO $ error "hello"` instead  of   `error "hello"`

**Comment by agocorona** [comment]
The last one do no pass the Testsuite of Transient-universe. It does past the testsuite of transient.

**Comment by agocorona** [comment]
After some tests it is strange that it is not a consequence of some distributed computing effect but a problem with applicatives.

This seems to work and catch all exceptions. It need some factorization to make it more sense of it. But this would come as we make more code with closures and continuations that is common to async, react and now, exceptions:
`ioexp`  is  an expression equivalent to  `mx`,  stripped down to the IO monad that attach am IO exception handler to it and all  the continuation.  One advantage is that liftIO no longer need an exception handler attached to it since ioexp catches every exception. This is a substantial reduction of boilerplate. 

 It needs more tests however.

```haskell

  onAnyException :: TransIO a -> (SomeException ->TransIO a) -> TransIO a
  onAnyException mx f=   ioexp  `onBack` f
       
  ioexp = Transient $ do 
    st <- get
    (mx,st') <- liftIO $ (runStateT (do

        case event st of 
          Nothing -> do
                r <- runTrans   mx  

                modify $ \s -> s{event= Just $ unsafeCoerce r}
                st' <- get
               
                runCont st'
                was <- getData `onNothing` return NoRemote
                when (was /= WasRemote) $ setData WasParallel

                return Nothing
          Just r -> do
               modify $ \s ->  s{event=Nothing}  
               return  $ unsafeCoerce r) st)
      `catch` \(e ::SomeException) ->  runStateT ( runTrans $ back e  ) st
    put st'
    return mx
```

**Comment by agocorona** [comment]
The catch need a catch. Otherwise, `back` which is the backtracking mechanism, is executed without exception handler

´´´haskell 
Just r -> do
                modify $ \s ->  s{event=Nothing}  
                return  $ unsafeCoerce r) st)
                   `catch` ch2 st
  ....

    ch2 st = \(e ::SomeException) -> do  -- recursive catch itself
                      -- return () !> "CATCH" 
                      runStateT ( runTrans $  back e ) st
                `catch` ch2 st
```
