### ISSUE TITLE
Strange hang with applicative code

### ISSUE THREAD

**Issue by mitchellwrosen** [transient-haskell/transient#73]
Hi, I have been reading through the transient tutorial and I happened upon a strange hang induced by the following code:

```haskell
main = keep (((,) <$> async (print 1) <*> liftIO (print 2)) *> liftIO (print 3))
```

For some reason, this prints `1` and `2`, but never `3`. However, using do-notation works fine:

```haskell
main = keep $ do
  _ <- (,) <$> async (print 1) <*> liftIO (print 2)
  liftIO (print 3)
```

Any idea what might be going on? Thank you!

**Comment by agocorona** [comment]
It run well in my box. what are your versions, platform ?

**Comment by mitchellwrosen** [comment]
Huh, now my example works fine for me, too. Maybe @seagreen or @nicklawls can reproduce the hang but for I can't.
